package url.shortener.domain

import io.micronaut.data.annotation.DateCreated
import io.micronaut.data.annotation.Relation
import java.time.Instant
import javax.persistence.Entity
import javax.persistence.GeneratedValue
import javax.persistence.Id

/*
Tables:
UrlMap
ID|INT, AUTOGENERATED
URL_CODE|VARCHAR
FULL_URL|VARCHAR
USER_ID|VARCHAR

Visits
ID|INT,
URL_CODE|VARCHAR, FOREIGN KEY
CLIENT_BROWSER| VARCHAR
IP_ADDRESS| VARCHAR
VISIT_DATETIME| DATETIME
 */

@Entity
data class UrlMap(@Id @GeneratedValue var id: Long = 0,
                  val urlCode: String,
                  val fullUrl: String,
                  val userId: String,
                  @DateCreated var createDtm: Instant = Instant.EPOCH)

@Entity
data class Visit(@Id @GeneratedValue var id: Long = 0,
                 val clientBrowser: String,
                 val ipAddress: String,
                 val urlCode: String,
                 @DateCreated var createDtm: Instant = Instant.EPOCH)
