package url.shortener.domain

import io.micronaut.data.annotation.MappedEntity
import javax.persistence.Entity
import javax.persistence.GeneratedValue
import javax.persistence.Id

/*
Tables:
UrlMap
ID|INT, AUTOGENERATED
URL_CODE|VARCHAR
FULL_URL|VARCHAR
USER_ID|VARCHAR

Visits
ID|INT, FOREIGN KEY
CLIENT_BROWSER| VARCHAR
IP_ADDRESS| VARCHAR
VISIT_DATETIME| DATETIME
 */

@Entity
data class UrlMap(@Id @GeneratedValue var id: Long?,
                  var urlCode: String,
                  var fullUrl: String,
                  var userId: String)
