GET http://localhost:8080/visits/ab3950a
Accept: application/json

###
POST http://localhost:8080/
Content-Type: application/json

{
  "url": "https:www.cnnmoney.com",
  "userId" : "outzider"
}

###

POST http://localhost:8080/
Content-Type: application/json

{
  "url": "https:www.cnn.com",
  "userId" : "outzider"
}

###

